[project]
name = "final-it"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "clypi>=1.8.1",
    "pickledb>=1.3.2",
    "prettytable>=3.17.0",
]
